enable-magisk-update = true

[Music-Extended]
app-name = "Music"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
patches-source = "SonzaiEkkusu/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[YouTube-Extended]
app-name = "YouTube"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
patches-source = "SonzaiEkkusu/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
