enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "apk"
# excluded-patches = ""
# included-patches = ""
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# version = "beta"

# [Music]
# build-mode = "apk"
# arch = "both"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# version = "beta"
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "beta"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'GmsCore support' 'Hide ads'"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
version = "beta"
excluded-patches = "'Bypass image region restrictions'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
