enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "X"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "X"
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"

[YouTube-E]
enabled = true
build-mode = "both"
module-prop-name = "youtube-E85"
patches-source = "E85Addict/revanced-patches"
excluded-patches = ""
included-patches = ""
patcher-args = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-E]
enabled = true
build-mode = "both"
module-prop-name = "music-E85"
arch = "arm64-v8a"
patches-source = "E85Addict/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
