[Music]
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"
version = "auto"

[YouTube]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "auto"
