[Music]
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"
version = "auto"

[YouTube]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube"
version = "auto"